services:
  - type: web
    name: spotify-vinyl-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false
      - key: DISCOGS_TOKEN
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
